version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
    ports:
      - 3001:3000
    depends_on:
      - db
    env_file: .env
    stdin_open: true
    tty: true
  
  db:
    image: postgres:latest
    volumes:
        - pg-data:/var/lib/postgresql/data
    env_file: .env
    ports:
        - 5432:5432


  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  bundle-cache: null
  pg-data: null