FROM ruby:2.5.3-alpine

RUN mkdir -p /app
WORKDIR /app

RUN apk --update --upgrade add git postgresql-dev imagemagick build-base xz-dev libc6-compat \
    nodejs \
    curl unzip \
    linux-headers \
    && rm -rf /var/cache/apk/*

COPY Gemfile /app
COPY Gemfile.lock /app

#RUN bundle install

COPY . /app

EXPOSE 3000